# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.

export ZSH="/Users/$USER/.oh-my-zsh"

#
plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    )

source $ZSH/oh-my-zsh.sh

. /usr/local/etc/profile.d/z.sh

fpath+=("$HOME/.zsh/pure")

# Change prompt to pure
autoload -U promptinit; promptinit

# Change pure directory the path color
zstyle :prompt:pure:path color yellow

# change pure prompt color
zstyle ':prompt:pure:prompt:*' color cyan

prompt pure

# Set Default editor to nvim
export EDITOR='nvim'

alias c="clear"
alias cdm="cd /Users/ud/Office/chartsdotcom"
alias zrc="code ~/.zshrc"
